version: "3"
services:
    api:
        build: api
        ports: 
            - 3000:80
    client:
        build: client
        ports: 
            - 4000:80
    nginx:
        image: nginx
        ports: 
            - 80:80
            - 443:443
        restart: always
        depends_on: 
            - client
            - api
        volumes: 
            - ./server/debug.conf:/etc/nginx/conf.d/default.conf