version: "3"
services:
    api:
        build: api
        ports: 
            - 3000:80
    client:
        build: client
        ports: 
            - 4000:80
    nginx:
        build: server
        ports: 
            - 80:80
            - 443:443
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
        restart: always
        depends_on: 
            - client
            - api