version: "3"
services:
    api:
        build: api
        ports: 
            - 3000:80
    nginx:
        build: server
        ports: 
            - 80:80
            - 443:443
        volumes: 
            - ./server/debug.conf:/etc/nginx/conf.d/default.conf
            - ./client:/usr/share/nginx/html
        restart: always
        depends_on:
            - api